 /******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the Ultrasonic driver
 *
 * Author: Yasmin Khaled
 *
 *******************************************************************************/

#include <util/delay.h> /* For the delay functions */
#include "icu.h"
#include "ultrasonic.h"
#include "gpio.h"
#include "common_macros.h"

uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;


/*
 * Description :
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the
 * GPIO driver.
 */
void Ultrasonic_init(void)
{
	/* Setup the direction for the trigger pin as output pin */
	GPIO_setupPinDirection(PORTB_ID, PIN5_ID, PIN_OUTPUT);

	/* Create configuration structure for ICU driver */
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};

	/* Initialize both the ICU driver */
	Icu_init(&Icu_Config);

	/* Set the Call back function pointer in the ICU driver */
	Icu_setCallBack(Ultrasonic_edgeProcessing);

}

/*
 * Description :
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
	/* Write one on the trigger pin to start the pulse */
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_HIGH);

	_delay_us(10);	/* delay for processing = 10 us */

	/* Write zero on the trigger pin to end the pulse */
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_LOW);
}



/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance = 0;
	/* Sending the trigger pulse */
	Ultrasonic_Trigger();

	/* Calculating the distance in cm */
	distance = g_timeHigh / 57.7;			//it should be 58.8 but there is 2cm difference so i made it 57.7

	return distance;

}



/*
 * Description :
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by
 * the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Clear the timer counter register to start measurements again */
		Icu_clearTimerValue();

		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);

	}

}
